gui:
  language: 'en'
  theme:
    # dark
    # ======
    selectedLineBgColor:
      - '#474e5d'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#f5a97f'
    #  light
    #  ======
    #selectedLineBgColor:
    #  - '#e5e5e5'
git:
  pagers:
    - colorArg: always
      #pager: delta --light --paging=never
      pager: delta --paging=never
